### ISSUE TITLE
Farmbot sent a malformed message

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/farmbot-web-frontend#171]
![image](https://cloud.githubusercontent.com/assets/23129562/21766387/74e9231a-d66e-11e6-8d82-fe6178dcfb56.png)

I was using OS 2.1.8 when one day this error came up. Today I flashed my SD-Cards two times with the newest OS (2.1.8) but still the same error. 
I'm using staging.farmbot.io.

**Comment by RickCarlino** [comment]
Hi, @AscendFB sorry about the trouble. Here's what's happening:

Although you were correct to reflash your device, you will need to compile an "edge" version of Farmbot OS from source since you are on the staging server.

You have a few options:

1. Flash the latest stable release and use production until these features are stable. I would highly recommend this. Although the staging server always has the latest features and is updated more frequently, it is not guaranteed to be 100% stable because we need to use it for testing new features.
2. Wait a day or so for the next stable release, which will have a fix for this issue.
3. Compile the `master` branch of [this fork](https://github.com/ConnorRigby/farmbot_os/tree/celery_script) by yourself from source (eg: don't use the precompiled `*.img` file on the releases page). You may still hit some issues because we are actively working on this right now.

I hope that helps! Please raise an issue if you hit any problems while compiling from source and we can help you from there. We should have this worked out within the next day or so.
