### ISSUE TITLE
More than one device being logged in and in charge

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/farmbot-web-frontend#216]
Hi all,

I think I noticed that if you are logged in with more than one device, the system gets confused.

I drove my bot today into the toolsbay, everything was properly programmed, not obvious problems so far. But I guess because I am programming the sequences on a desktop PC inside and then going outside and starting the testsequence on my iPhone something gets mixed up. There is not difference between firefox or chrome on the mobile.

Is there something how I could help you to debug? Hard to do that if the log is not working at all...

**Comment by RickCarlino** [comment]
@Klimbim1 FarmBot OS does not support multiple user sessions right now. I recommend logging out of one account before starting a new session in a different device, and also making sure to push the `"SYNC"` button after saving changes.

**Comment by Klimbim1** [comment]
@RickCarlino: wouldn´t it be an idea to intercept the problems arising through these multiple sessions if you intercept multi log ins? Just tell that you are already logged in another device?

The problem is, I guess many people are using some sort of PC inside and something mobile outside... They would need to know that it is currently not supported. Otherwise they are having interesting things going on like me, but don´t know that they are related to multiple user sessions...

**Comment by RickCarlino** [comment]
It's a very good idea, @Klimbim1 and we hope to support multi-user bots in the future. Right now, the system was designed with the assumption that there is only one active user session per bot. There are no tracking mechanisms for sessions at this time, which is why I recommend not controlling the bot from two different user sessions. In the mean time, I may add [version locking](http://guides.rubyonrails.org/active_record_querying.html#pessimistic-locking) to a future release to hopefully clear up confusion about this.

With regards to your question about syncing, the bot avoids changing local records (sequences, regimens, plants, etc) without pressing the "SYNC" button first. There were a number of factors we had to consider when we made this decision, but ultimately we decided that it is better to *not* change the data on the device unless the user explicitly presses the "sync" button.

To answer your question though, yes, if you make changes to sequences or regimens you will need to push the "SYNC" button before logging out. You could also "save", log out and then "sync" from another device as well.
