### ISSUE TITLE
Connection refused: Not authorized

### ISSUE THREAD

**Issue by eamonpenland** [FarmBot/farmbot-web-frontend#96]
Hey! Just cloned the repo and pointed the server url to the remote staging api (//my.farmbot.io). I created an account and was logged in to the dashboard. I keep getting a react dev tools popup saying Connection refused: Not authorized. Any idea what is going on?

**Comment by RickCarlino** [comment]
Eamon,

Thanks for the heads up! Your next step would be to Flash an Arduino with the [latest stable firmware](https://github.com/FarmBot/farmbot-arduino-firmware/releases) and hook it up to a machine running the [latest stable RPi software](https://github.com/FarmBot/farmbot-raspberry-pi-controller/releases). You'll need to run `setup.rb` on the Pi also (or just run it off your desktop for testing purposes). Did you get that far yet? My guess is that it's not connecting to MQTT properly because no device is configured.

Sorry for the vagueness on the setup process- we will be revamping the onboarding setup soon!

Does that help? Please let me know if you have any more issues and I can re-open accordingly.
